#!/bin/busybox sh
echo "---> WELCOME TO tripledoomers BUSYBOX! <---"
/bin/busybox --install -s /bin
/bin/mount -t sysfs sysfs /sys
/bin/mount -t proc proc /proc
/bin/mount -t devtmpfs devtmpfs /dev
/bin/sysctl -w kernel.printk="2 4 1 7"
/bin/sh
echo "---> tripledoomers BUSYBOX IS SHUTTING DOWN! <---"
/bin/poweroff -f
